api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint

graphql:
    path: /api/graphqle
    controller: api_platform.graphql.action.graphiql

graphql_playground:
    path: /api/graphql_playg
    controller: api_platform.graphql.action.graphql_playground